apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-for-frontend
  namespace: realtime-microservices
  labels:
    app: notification-producer
spec:
  selector:
    matchLabels:
      app: backend-for-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-for-frontend
    spec:
      containers:
      - name: backend-for-frontend-container
        imagePullPolicy: Always
        image: ${DockerRegistryUrl}/backend-for-frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-for-frontend
  namespace: realtime-microservices
spec:
  ports:
  - port: 80
  selector:
    app: backend-for-frontend