apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-for-frontend
  namespace: realtime-microservices
  labels:
    app: notification-producer
spec:
  selector:
    matchLabels:
      app: backend-for-frontend
  replicas: 10 # to showcase websockets working we need multiple instances
  template:
    metadata:
      labels:
        app: backend-for-frontend
    spec:
      containers:
      - name: backend-for-frontend-container
        imagePullPolicy: Always
        image: ${DockerRegistryUrl}/backend-for-frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-for-frontend
  namespace: realtime-microservices
spec:
  ports:
  - port: 80
  selector:
    app: backend-for-frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bff-ingress
  namespace: realtime-microservices
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: REALTIMESERVERID
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: backend-for-frontend
          servicePort: 80
      - path: /hubs
        backend:
          serviceName: backend-for-frontend
          servicePort: 80